apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-bstwxkmy
  janus-idp.io/tekton: go-bstwxkmy
  backstage.io/kubernetes-id: go-bstwxkmy
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-bstwxkmy
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
